### ISSUE TITLE
RNIP Issue Triage Group 1

### ISSUE THREAD

**Issue by lukebrandonfarrell** [react-native-image-picker/react-native-image-picker#1983]
### Description

This is a triage group to discuss and prioritise major issues which are affecting the react-native-image-picker library. Looking for help to debug, prioritise and fix some of these outstanding issues.

### Issues

- [ ] [Picker returns empty array of assets when iPhone 13 Pro raw (.dng) photo is selected](#1980)
- [ ] [Picker freezes on iPhone 13 when CameraRoll has 10,000+ photos](#1973)
- [ ] [No response on swipe down camera roll](#1903)
- [ ] Assets coming back as [] when selecting a video on iOS 15 testing on Simulator (#1902)
- [ ] Video quality does NOT affect size on iOS (#1908)
